### ISSUE TITLE
How to use multiple animations

### ISSUE THREAD

**Issue by linglong233** [TimLee9024/MCglTF#2]

**Comment by TimLee9024** [comment]
In [example code](https://github.com/TimLee9024/MCglTF-Example/blob/78099cb95ec03073f418fd798a077a5cfed9b473/src/main/java/com/timlee9024/mcgltf/example/ItemStackTileEntityRendererBlockItemExample.java#L87), it play all animation clips simultaneously in the glTF file.
```java
for(Animation animation : animations) {
	animation.update(net.minecraftforge.client.model.animation.Animation.getWorldTime(mc.level, net.minecraftforge.client.model.animation.Animation.getPartialTickTime()) % animation.getEndTimeS());
}
```
You can determine which animation clip need to play based on various condition.

You can also add `name` or `extras` in each animation clip and get these properties (object from getExtras() need to deserialize by Gson) via `getAnimationModels()` during `onModelLoaded(RenderedGltfModel renderedModel)`. This give you a concept of ID or filter/categorizer for animation clips, if the order and count of animation clips is unspecifed for a glTF model.
***
Chinese translation:
在[範例程式碼](https://github.com/TimLee9024/MCglTF-Example/blob/78099cb95ec03073f418fd798a077a5cfed9b473/src/main/java/com/timlee9024/mcgltf/example/ItemStackTileEntityRendererBlockItemExample.java#L87)中，預設是同時撥放所有的動畫片段：
```java
for(Animation animation : animations) {
	animation.update(net.minecraftforge.client.model.animation.Animation.getWorldTime(mc.level, net.minecraftforge.client.model.animation.Animation.getPartialTickTime()) % animation.getEndTimeS());
}
```

你可以根據一些條件(例如物品的NBT、實體或方塊實體的成員變數)，來決定需要撥放的動畫片段。

假如你的glTF模型的動畫片段的數量和排序是不固定的，你可以在glTF模型檔的每個動畫片段中加入`name`或`extras`等額外資料，並在`onModelLoaded(RenderedGltfModel renderedModel)`時透過`getAnimationModels()`來存取並反序列化其中的資料(從`getExtras()`取得的物件要透過Gson反序列化)，這些資料即可成為該動畫片段能撥放的附加條件之一。

**Comment by linglong233** [comment]
OK Thanks
